---
- hosts: docker
  become: true
  tasks:
  - name: Copy files into Docker
    copy:
      src: Dockerfile
      dest: /home/ubuntu
  - name: Copy artifact
    copy:
      src: lexus-app.war
      dest: /home/ubuntu
